//
//  StoreRouter.swift
//  PruebaLiverpool
//
//  Created Osvaldo Salas Palomo on 10/02/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Osva
//

import UIKit

class StoreRouter: StoreWireframeProtocol {
    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        let view = StoreViewController(nibName: "StoreViewController", bundle: .local)
        let interactor = StoreInteractor()
        let router = StoreRouter()
        let presenter = StorePresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}

extension Bundle {
    static func bundleOfSelf() -> Bundle{
        return Bundle(for: StoreRouter.self)
    }
    
    static let local:Bundle = Bundle.init(for: StoreRouter.self)
}
