//
//  StorePresenter.swift
//  PruebaLiverpool
//
//  Created Osvaldo Salas Palomo on 10/02/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Osva
//

import UIKit

class StorePresenter {
    weak private var view: StoreViewProtocol?
    var interactor: StoreInteractorInputProtocol?
    private let router: StoreWireframeProtocol

    init(interface: StoreViewProtocol, interactor: StoreInteractorInputProtocol?, router: StoreWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

extension StorePresenter: StorePresenterProtocol {
    func getOrderTypes() -> [FilterUrl] {
        var array = [FilterUrl]()
        array.append(.Predefinida)
        array.append(.Mayorprecio)
        array.append(.Menorprecio)
        return array
    }
    
    func willGetData(search: String, page: String, filtro:FilterUrl) {
        interactor?.getData(search: search, page: page, filtro: filtro)
    }
}

extension StorePresenter: StoreInteractorOutputProtocol {
    func willShowData(data: StoreModel) {
        view?.showData(data: data)
    }
    
    func willShowError() {
        view?.showError()
    }
}
