//
//  StoreProtocols.swift
//  PruebaLiverpool
//
//  Created Osvaldo Salas Palomo on 10/02/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Osva
//

import Foundation

//MARK: Presenter -> Router
protocol StoreWireframeProtocol: AnyObject {
    
}

//MARK: View -> Presenter
protocol StorePresenterProtocol: AnyObject {
    var interactor: StoreInteractorInputProtocol? { get set }
    func willGetData(search: String, page: String, filtro:FilterUrl)
    func getOrderTypes() -> [FilterUrl]
}

//MARK: Interactor -> Presenter
protocol StoreInteractorOutputProtocol: AnyObject {
    func willShowData(data: StoreModel)
    func willShowError()
    
}

//MARK: Presenter -> Interactor
protocol StoreInteractorInputProtocol: AnyObject {
    var presenter: StoreInteractorOutputProtocol?  { get set }
    func getData(search: String, page: String, filtro:FilterUrl)
}

//MARK: Presenter -> View
protocol StoreViewProtocol: AnyObject {
    var presenter: StorePresenterProtocol?  { get set }
    func showData(data: StoreModel)
    func showError()
}
